ap:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3307
    database: appointment_register
    username: root
    password: 123456
  redis:
      host: localhost
      port: 16379
      password: ""
      timeout: 1000
  jwt:
    key: appointment_register_development_secret_key_that_is_long_enough_for_hs512_algorithm_minimum_64_characters_required
    ttl: 604800000

order:
  prefix: "LYLZX"
